python omnigraph/train/train_stage2B.py \
  --scene_graphs data/vg/contents/sceneGraphs/scene_graphs.json \
  --regions data/vg/contents/regionDescriptions/region_descriptions.json \
  --stage2A_ckpt checkpoints_projector_vg/stage2A/stage2A-step=0005000-val_loss=2.607.ckpt \
  --gpu 0 \
  --batch_size 2 \
  --precision 32 \
  --max_length 256 \
  --lr 2e-5 \
  --max_steps 20000 \
  --val_ratio 0.001 \
  --patience 2 --min_delta 0.01 \
  --save_dir checkpoints_projector_vg/stage2B