#!/usr/bin/env bash
set -euo pipefail

WORKDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$WORKDIR"

map_var() {
  local old_name="$1"
  local new_name="$2"
  if [ -n "${!old_name+x}" ] && [ -z "${!new_name+x}" ]; then
    export "$new_name=${!old_name}"
  fi
}

map_var SCENE_GRAPHS VG_SCENE_GRAPHS
map_var REGIONS VG_REGIONS
map_var EXTRA_GRAPHS EXTRA_SCENE_GRAPHS
map_var PSEUDO_SCENE_GRAPHS EXTRA_SCENE_GRAPHS
map_var STAGE1_CKPT STAGE1_QFORMER_CKPT
map_var BOOTSTRAP_MODE STAGE2A_BOOTSTRAP_MODE
map_var STAGE2A_BOOTSTRAP STAGE2A_BOOTSTRAP_MODE
map_var GRAPH_TOKENIZER GRAPH_TOKENIZER_TYPE
map_var TOKENIZER_TYPE GRAPH_TOKENIZER_TYPE
map_var PERCEIVER_LATENTS PERCEIVER_NUM_LATENTS
map_var PERCEIVER_LAYERS PERCEIVER_NUM_LAYERS
map_var PERCEIVER_HEADS PERCEIVER_NUM_HEADS
map_var PERCEIVER_FF PERCEIVER_FF_MULT
map_var PERCEIVER_DROP PERCEIVER_DROPOUT
map_var SAVE_DIR STAGE2A_DIR
map_var BATCH_SIZE S2A_BATCH_SIZE
map_var PRECISION S2A_PRECISION
map_var MAX_LENGTH S2A_MAX_LENGTH
map_var MAX_GRAPH_TOKENS S2A_MAX_GRAPH_TOKENS
map_var NUM_WORKERS S2A_NUM_WORKERS
map_var ACCUM_GRAD_BATCHES S2A_ACCUM_GRAD_BATCHES
map_var VAL_CHECK_INTERVAL S2A_VAL_CHECK_INTERVAL
map_var VAL_RATIO S2A_VAL_RATIO
map_var PATIENCE S2A_PATIENCE
map_var MIN_DELTA S2A_MIN_DELTA
map_var LR S2A_LR
map_var MAX_STEPS S2A_MAX_STEPS
map_var GRAPH_QA_MAX_PER_IMAGE S2A_GRAPH_QA_MAX_PER_IMAGE
map_var GRAPH_QA_REPEAT S2A_GRAPH_QA_REPEAT
map_var PSEUDO_GRAPH_QA_MAX_PER_IMAGE S2A_PSEUDO_GRAPH_QA_MAX_PER_IMAGE
map_var PSEUDO_GRAPH_QA_REPEAT S2A_PSEUDO_GRAPH_QA_REPEAT
map_var GRAPH_AUX_LOSS_WEIGHT S2A_GRAPH_AUX_LOSS_WEIGHT
map_var XTC_WEIGHT S2A_XTC_WEIGHT
map_var XTM_WEIGHT S2A_XTM_WEIGHT

export PIPELINE_MODE=graph_bootstrap
exec bash "$WORKDIR/scripts/train/run_4090_gqa_sprint.sh"
