#!/usr/bin/env bash
set -euo pipefail

WORKDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$WORKDIR"

map_var() {
  local old_name="$1"
  local new_name="$2"
  if [ -n "${!old_name+x}" ] && [ -z "${!new_name+x}" ]; then
    export "$new_name=${!old_name}"
  fi
}

map_var SCENE_GRAPHS VG_SCENE_GRAPHS
map_var REGIONS VG_REGIONS
map_var IMAGE_ROOT VG_IMAGE_ROOT
map_var GRAPH_TOKENIZER GRAPH_TOKENIZER_TYPE
map_var TOKENIZER_TYPE GRAPH_TOKENIZER_TYPE
map_var PERCEIVER_LATENTS PERCEIVER_NUM_LATENTS
map_var PERCEIVER_LAYERS PERCEIVER_NUM_LAYERS
map_var PERCEIVER_HEADS PERCEIVER_NUM_HEADS
map_var PERCEIVER_FF PERCEIVER_FF_MULT
map_var PERCEIVER_DROP PERCEIVER_DROPOUT
map_var SAVE_DIR STAGE3_DIR
map_var BATCH_SIZE S3_BATCH_SIZE
map_var PRECISION S3_PRECISION
map_var MAX_LENGTH S3_MAX_LENGTH
map_var MAX_GRAPH_TOKENS S3_MAX_GRAPH_TOKENS
map_var MAX_VISION_TOKENS S3_MAX_VISION_TOKENS
map_var NUM_WORKERS S3_NUM_WORKERS
map_var ACCUM_GRAD_BATCHES S3_ACCUM_GRAD_BATCHES
map_var VAL_CHECK_INTERVAL S3_VAL_CHECK_INTERVAL
map_var VAL_RATIO S3_VAL_RATIO
map_var PATIENCE S3_PATIENCE
map_var MIN_DELTA S3_MIN_DELTA
map_var LR S3_LR
map_var MAX_STEPS S3_MAX_STEPS
map_var GRAPH_QA_MAX_PER_IMAGE S3_GRAPH_QA_MAX_PER_IMAGE
map_var GRAPH_QA_REPEAT S3_GRAPH_QA_REPEAT
map_var GRAPH_AUX_LOSS_WEIGHT S3_GRAPH_AUX_LOSS_WEIGHT
map_var XTC_WEIGHT S3_XTC_WEIGHT
map_var XTM_WEIGHT S3_XTM_WEIGHT

export PIPELINE_MODE=stage3
exec bash "$WORKDIR/scripts/train/run_4090_gqa_sprint.sh"
