#!/usr/bin/env bash
set -euo pipefail

# Fast-stop full run:
# graph_bootstrap -> graph_refine -> multimodal_tune -> GQA eval
# Goal: faster convergence decisions with frequent/lightweight validation and aggressive early-stop.

WORKDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$WORKDIR"

PYTHON_BIN=${PYTHON_BIN:-python}
PROFILE=${PROFILE:-pro6000}
GPU=${GPU:-0}
DATA_CONFIG=${DATA_CONFIG:-configs/train/data_paths.server.json}

if [ ! -f "$DATA_CONFIG" ]; then
  echo "[FastStop] data config not found: $DATA_CONFIG"
  exit 1
fi

# Keep full pipeline behavior, but bias for faster turnaround.
S2A_MAX_STEPS=${S2A_MAX_STEPS:-40000}
S2B_MAX_STEPS=${S2B_MAX_STEPS:-30000}
S3_MAX_STEPS=${S3_MAX_STEPS:-18000}

S2A_VAL_CHECK_INTERVAL=${S2A_VAL_CHECK_INTERVAL:-800}
S2B_VAL_CHECK_INTERVAL=${S2B_VAL_CHECK_INTERVAL:-800}
S3_VAL_CHECK_INTERVAL=${S3_VAL_CHECK_INTERVAL:-600}

S2A_LIMIT_VAL_BATCHES=${S2A_LIMIT_VAL_BATCHES:-0.01}
S2B_LIMIT_VAL_BATCHES=${S2B_LIMIT_VAL_BATCHES:-0.01}
S3_LIMIT_VAL_BATCHES=${S3_LIMIT_VAL_BATCHES:-0.01}

S2A_PATIENCE=${S2A_PATIENCE:-5}
S2B_PATIENCE=${S2B_PATIENCE:-6}
S3_PATIENCE=${S3_PATIENCE:-5}

S2A_MIN_DELTA=${S2A_MIN_DELTA:-0.0015}
S2B_MIN_DELTA=${S2B_MIN_DELTA:-0.0010}
S3_MIN_DELTA=${S3_MIN_DELTA:-0.0010}

S2A_CHECKPOINT_EVERY_N_STEPS=${S2A_CHECKPOINT_EVERY_N_STEPS:-400}
S2B_CHECKPOINT_EVERY_N_STEPS=${S2B_CHECKPOINT_EVERY_N_STEPS:-400}
S3_CHECKPOINT_EVERY_N_STEPS=${S3_CHECKPOINT_EVERY_N_STEPS:-400}

# Throughput-oriented defaults on large cards.
S2A_ACCUM_GRAD_BATCHES=${S2A_ACCUM_GRAD_BATCHES:-1}
S2B_ACCUM_GRAD_BATCHES=${S2B_ACCUM_GRAD_BATCHES:-1}
S3_ACCUM_GRAD_BATCHES=${S3_ACCUM_GRAD_BATCHES:-1}
S2A_ENABLE_LLM_GRADIENT_CHECKPOINTING=${S2A_ENABLE_LLM_GRADIENT_CHECKPOINTING:-0}
S2B_ENABLE_LLM_GRADIENT_CHECKPOINTING=${S2B_ENABLE_LLM_GRADIENT_CHECKPOINTING:-0}
S3_ENABLE_LLM_GRADIENT_CHECKPOINTING=${S3_ENABLE_LLM_GRADIENT_CHECKPOINTING:-0}

S2A_NUM_WORKERS=${S2A_NUM_WORKERS:-12}
S2B_NUM_WORKERS=${S2B_NUM_WORKERS:-12}
S3_NUM_WORKERS=${S3_NUM_WORKERS:-8}
S2A_PREFETCH_FACTOR=${S2A_PREFETCH_FACTOR:-8}
S2B_PREFETCH_FACTOR=${S2B_PREFETCH_FACTOR:-8}
S3_PREFETCH_FACTOR=${S3_PREFETCH_FACTOR:-8}

# Faster data mix for first-pass convergence.
S2A_GRAPH_QA_REPEAT=${S2A_GRAPH_QA_REPEAT:-2}
S2B_GRAPH_QA_REPEAT=${S2B_GRAPH_QA_REPEAT:-4}
S3_GRAPH_QA_REPEAT=${S3_GRAPH_QA_REPEAT:-2}

# Stage3 v2 defaults (curriculum + gating + modality dropout).
S3_ENABLE_STAGE3_CURRICULUM=${S3_ENABLE_STAGE3_CURRICULUM:-1}
S3_CURRICULUM_PHASE_A_STEPS=${S3_CURRICULUM_PHASE_A_STEPS:-1200}
S3_CURRICULUM_PHASE_B_STEPS=${S3_CURRICULUM_PHASE_B_STEPS:-6000}
S3_PHASE_A_ALIGN_SCALE=${S3_PHASE_A_ALIGN_SCALE:-1.35}
S3_PHASE_C_ALIGN_SCALE=${S3_PHASE_C_ALIGN_SCALE:-0.60}
S3_PHASE_A_AUX_SCALE=${S3_PHASE_A_AUX_SCALE:-0.80}
S3_PHASE_C_AUX_SCALE=${S3_PHASE_C_AUX_SCALE:-1.00}
S3_TRAIN_GRAPH_DROP_PROB=${S3_TRAIN_GRAPH_DROP_PROB:-0.06}
S3_TRAIN_VISION_DROP_PROB=${S3_TRAIN_VISION_DROP_PROB:-0.06}
S3_ENABLE_QA_TYPE_MODALITY_GATE=${S3_ENABLE_QA_TYPE_MODALITY_GATE:-1}

exec "$PYTHON_BIN" scripts/train/infra_launcher.py \
  --profile "$PROFILE" \
  --mode full \
  --gpu "$GPU" \
  --data-config "$DATA_CONFIG" \
  --preflight \
  --set AUTO_RESUME_ON_OOM=1 \
  --set AUTO_BATCH_RETRY_ON_OOM=1 \
  --set RUN_ROUND2_ON_FAIL=0 \
  --set S2A_MAX_STEPS="$S2A_MAX_STEPS" \
  --set S2B_MAX_STEPS="$S2B_MAX_STEPS" \
  --set S3_MAX_STEPS="$S3_MAX_STEPS" \
  --set S2A_VAL_CHECK_INTERVAL="$S2A_VAL_CHECK_INTERVAL" \
  --set S2B_VAL_CHECK_INTERVAL="$S2B_VAL_CHECK_INTERVAL" \
  --set S3_VAL_CHECK_INTERVAL="$S3_VAL_CHECK_INTERVAL" \
  --set S2A_LIMIT_VAL_BATCHES="$S2A_LIMIT_VAL_BATCHES" \
  --set S2B_LIMIT_VAL_BATCHES="$S2B_LIMIT_VAL_BATCHES" \
  --set S3_LIMIT_VAL_BATCHES="$S3_LIMIT_VAL_BATCHES" \
  --set S2A_PATIENCE="$S2A_PATIENCE" \
  --set S2B_PATIENCE="$S2B_PATIENCE" \
  --set S3_PATIENCE="$S3_PATIENCE" \
  --set S2A_MIN_DELTA="$S2A_MIN_DELTA" \
  --set S2B_MIN_DELTA="$S2B_MIN_DELTA" \
  --set S3_MIN_DELTA="$S3_MIN_DELTA" \
  --set S2A_CHECKPOINT_EVERY_N_STEPS="$S2A_CHECKPOINT_EVERY_N_STEPS" \
  --set S2B_CHECKPOINT_EVERY_N_STEPS="$S2B_CHECKPOINT_EVERY_N_STEPS" \
  --set S3_CHECKPOINT_EVERY_N_STEPS="$S3_CHECKPOINT_EVERY_N_STEPS" \
  --set S2A_ACCUM_GRAD_BATCHES="$S2A_ACCUM_GRAD_BATCHES" \
  --set S2B_ACCUM_GRAD_BATCHES="$S2B_ACCUM_GRAD_BATCHES" \
  --set S3_ACCUM_GRAD_BATCHES="$S3_ACCUM_GRAD_BATCHES" \
  --set S2A_ENABLE_LLM_GRADIENT_CHECKPOINTING="$S2A_ENABLE_LLM_GRADIENT_CHECKPOINTING" \
  --set S2B_ENABLE_LLM_GRADIENT_CHECKPOINTING="$S2B_ENABLE_LLM_GRADIENT_CHECKPOINTING" \
  --set S3_ENABLE_LLM_GRADIENT_CHECKPOINTING="$S3_ENABLE_LLM_GRADIENT_CHECKPOINTING" \
  --set S2A_NUM_WORKERS="$S2A_NUM_WORKERS" \
  --set S2B_NUM_WORKERS="$S2B_NUM_WORKERS" \
  --set S3_NUM_WORKERS="$S3_NUM_WORKERS" \
  --set S2A_PREFETCH_FACTOR="$S2A_PREFETCH_FACTOR" \
  --set S2B_PREFETCH_FACTOR="$S2B_PREFETCH_FACTOR" \
  --set S3_PREFETCH_FACTOR="$S3_PREFETCH_FACTOR" \
  --set S2A_GRAPH_QA_REPEAT="$S2A_GRAPH_QA_REPEAT" \
  --set S2B_GRAPH_QA_REPEAT="$S2B_GRAPH_QA_REPEAT" \
  --set S3_GRAPH_QA_REPEAT="$S3_GRAPH_QA_REPEAT" \
  --set S3_ENABLE_STAGE3_CURRICULUM="$S3_ENABLE_STAGE3_CURRICULUM" \
  --set S3_CURRICULUM_PHASE_A_STEPS="$S3_CURRICULUM_PHASE_A_STEPS" \
  --set S3_CURRICULUM_PHASE_B_STEPS="$S3_CURRICULUM_PHASE_B_STEPS" \
  --set S3_PHASE_A_ALIGN_SCALE="$S3_PHASE_A_ALIGN_SCALE" \
  --set S3_PHASE_C_ALIGN_SCALE="$S3_PHASE_C_ALIGN_SCALE" \
  --set S3_PHASE_A_AUX_SCALE="$S3_PHASE_A_AUX_SCALE" \
  --set S3_PHASE_C_AUX_SCALE="$S3_PHASE_C_AUX_SCALE" \
  --set S3_TRAIN_GRAPH_DROP_PROB="$S3_TRAIN_GRAPH_DROP_PROB" \
  --set S3_TRAIN_VISION_DROP_PROB="$S3_TRAIN_VISION_DROP_PROB" \
  --set S3_ENABLE_QA_TYPE_MODALITY_GATE="$S3_ENABLE_QA_TYPE_MODALITY_GATE" \
  "$@"

